apiVersion: v1
kind: Namespace
metadata:
  name: razeedeploy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: razeedeploy-sa
  namespace: razeedeploy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: razeedeploy-admin-cr
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: razeedeploy-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: razeedeploy-admin-cr
subjects:
- kind: ServiceAccount
  name: razeedeploy-sa
  namespace: razeedeploy
---
apiVersion: batch/v1
kind: Job
metadata:
  name: razeedeploy-job
  namespace: razeedeploy
spec:
  template:
    spec:
      serviceAccountName: razeedeploy-sa
      containers:
      - name: razeedeploy-job
        image: "quay.io/razee/razeedeploy-delta:1.0.0"
        command: ["node", "src/install"]
        args: ["--namespace=razeedeploy", "--remoteresource"]
        # see README.md for args options. https://github.com/razee-io/razeedeploy-delta/blob/master/README.md
      restartPolicy: Never
  backoffLimit: 2
